### ISSUE TITLE
dp.analyse_delphes_samples() 

### ISSUE THREAD

**Issue by irinaespejo** [johannbrehmer/madminer#236]
Hi all,
I'm getting this error when I run `dp.analyse_delphes_samples(reference_benchmark=benchmark)`, where `benchmark = 'sm'`  I also get it if the benchmark is other than `'sm'`. Below the error I give more info about previous lines. Do you know what's the problem? Thank you!

############################################
Traceback (most recent call last):
File "code/delphes.py", line 67, in <module>
dp.analyse_delphes_samples(reference_benchmark=benchmark, parse_lhe_events_as_xml=False)
File "/usr/local/lib/python2.7/dist-packages/madminer/delphes.py", line 600, in analyse_delphes_samples
acceptance_pt_min_j=self.acceptance_pt_min_j,
File "/usr/local/lib/python2.7/dist-packages/madminer/utils/interfaces/delphes_root.py", line 41, in parse_delphes_root_file
root_file = uproot.open(delphes_sample_file)
File "/usr/local/lib/python2.7/dist-packages/uproot/rootio.py", line 74, in open
return ROOTDirectory.read(openfcn(path), **options)
File "/usr/local/lib/python2.7/dist-packages/uproot/rootio.py", line 71, in <lambda>
openfcn = lambda path: MemmapSource(path, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/uproot/source/memmap.py", line 45, in __init__
self._source = numpy.memmap(self.path, dtype=numpy.uint8, mode="r")
File "/usr/local/lib/python2.7/dist-packages/numpy/core/memmap.py", line 225, in __new__
f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
File "/usr/local/lib/python2.7/dist-packages/numpy/compat/py3k.py", line 237, in os_fspath
"not " + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not unicode
###########################################

before that I added these observables with `dp.add_observable()` and cuts `dp.add_cut()`:

`observables:
  - name: 'pt_j1'
    definition: 'j[0].pt'
    required: False
    default: 0.

  - name: 'delta_phi_jj'
    definition: '(j[0].phi() - j[1].phi()) * (-1. + 2.*float(j[0].eta > j[1].eta))'
    required: True
    default: 

cuts:
  - cut: 1
    expression: 'pt_j1 > 30.' `

**Comment by irinaespejo** [comment]
Hi Johann, I was using versions (1.16.0, 2.7) just like the numpy bug you linked. I've forced numpy to downgrade to 1.15.4, because before with the requirement "numpy>=1.13.0" it automatically installed the newest version. That particular bug has disappeared.

**Comment by irinaespejo** [comment]
Thanks a lot!

**Comment by johannbrehmer** [comment]
a9c57f4dca09270ca3623c722a296e86d737c99f should solve this issue also for numpy 1.16.0 and Python 2.7...
